bank: main4.cpp account.hpp account.cpp savings_account.hpp savings_account.cpp checking_account.hpp checking_account.cpp
	g++ -Wall main4.cpp account.cpp savings_account.cpp checking_account.cpp -o bank
	./bank